
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package py01compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 25;
  public static final int MINUSM = 5;
  public static final int STRING_LITERAL = 12;
  public static final int POT = 7;
  public static final int BOOOLEANF = 56;
  public static final int CHAR = 29;
  public static final int CASE = 40;
  public static final int STRINGC = 30;
  public static final int INT = 27;
  public static final int FOR = 36;
  public static final int MINUS = 4;
  public static final int PARAM = 47;
  public static final int NOT = 21;
  public static final int RANGE = 38;
  public static final int IN = 37;
  public static final int ENDLINE = 55;
  public static final int DIV = 6;
  public static final int GREATERT = 17;
  public static final int PLUS = 2;
  public static final int MAIN = 46;
  public static final int IF = 33;
  public static final int PARENTC = 51;
  public static final int PARENTA = 50;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int PLUSP = 3;
  public static final int COMA = 57;
  public static final int STRING_SINGLE = 13;
  public static final int PARENTCC = 53;
  public static final int EQEQ = 14;
  public static final int PARENTCA = 52;
  public static final int GREATERE = 19;
  public static final int MOD = 8;
  public static final int BREAK = 15;
  public static final int EQ = 16;
  public static final int PRINTF = 44;
  public static final int SWITCH = 39;
  public static final int TIMES = 9;
  public static final int LOWERT = 18;
  public static final int LOC = 42;
  public static final int ELSE = 34;
  public static final int FUNC = 45;
  public static final int READ = 48;
  public static final int WHILE = 35;
  public static final int NOTEQUALS = 22;
  public static final int DEFAULT = 49;
  public static final int FLOAT = 28;
  public static final int CONJUNTION = 23;
  public static final int UNDERS = 54;
  public static final int LOWERE = 20;
  public static final int DISJUNTION = 24;
  public static final int GLOB = 41;
  public static final int FALSE = 32;
  public static final int FLOTANTE = 26;
  public static final int INTEGER_LITERAL = 10;
  public static final int IDENTIFIER = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "PLUSP",
  "MINUS",
  "MINUSM",
  "DIV",
  "POT",
  "MOD",
  "TIMES",
  "INTEGER_LITERAL",
  "IDENTIFIER",
  "STRING_LITERAL",
  "STRING_SINGLE",
  "EQEQ",
  "BREAK",
  "EQ",
  "GREATERT",
  "LOWERT",
  "GREATERE",
  "LOWERE",
  "NOT",
  "NOTEQUALS",
  "CONJUNTION",
  "DISJUNTION",
  "SEP",
  "FLOTANTE",
  "INT",
  "FLOAT",
  "CHAR",
  "STRINGC",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "IN",
  "RANGE",
  "SWITCH",
  "CASE",
  "GLOB",
  "LOC",
  "RETURN",
  "PRINTF",
  "FUNC",
  "MAIN",
  "PARAM",
  "READ",
  "DEFAULT",
  "PARENTA",
  "PARENTC",
  "PARENTCA",
  "PARENTCC",
  "UNDERS",
  "ENDLINE",
  "BOOOLEANF",
  "COMA"
  };
}

